services:
  mysql:
    image: mysql:8.4
    container_name: cbs-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema_booking
      MYSQL_USER: cbs
      MYSQL_PASSWORD: cbs_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: