-- AlterTable
ALTER TABLE `User` MODIFY COLUMN `role` ENUM('USER', 'ADMIN', 'CUSTOMER') NOT NULL DEFAULT 'CUSTOMER';
UPDATE `User` SET `role` = 'CUSTOMER' WHERE `role` = 'USER';
ALTER TABLE `User` MODIFY COLUMN `role` ENUM('CUSTOMER', 'ADMIN') NOT NULL DEFAULT 'CUSTOMER';
ALTER TABLE `User` MODIFY COLUMN `status` ENUM('ACTIVE', 'BLOCKED') NOT NULL DEFAULT 'ACTIVE';
